BEGIN;

-- btree_gist lets PostgreSQL enforce non-overlapping SCD Type 2 periods for
-- BIGINT and VARCHAR source identifiers.
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;

CREATE SCHEMA IF NOT EXISTS warehouse;
SET search_path TO warehouse, public;
SET TIME ZONE 'UTC';


-- ---------------------------------------------------------------------------
-- ETL control table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS etl_batch (
    batch_id UUID PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    batch_status VARCHAR(20) NOT NULL,
    mysql_watermark_from TIMESTAMPTZ,
    mysql_watermark_to TIMESTAMPTZ,
    mongo_watermark_from TIMESTAMPTZ,
    mongo_watermark_to TIMESTAMPTZ,
    input_row_count BIGINT NOT NULL DEFAULT 0,
    loaded_row_count BIGINT NOT NULL DEFAULT 0,
    rejected_row_count BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,

    CONSTRAINT ck_etl_batch_status
        CHECK (batch_status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_etl_batch_completed_at
        CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_etl_batch_mysql_watermark
        CHECK (
            mysql_watermark_from IS NULL
            OR mysql_watermark_to IS NULL
            OR mysql_watermark_to >= mysql_watermark_from
        ),
    CONSTRAINT ck_etl_batch_mongo_watermark
        CHECK (
            mongo_watermark_from IS NULL
            OR mongo_watermark_to IS NULL
            OR mongo_watermark_to >= mongo_watermark_from
        ),
    CONSTRAINT ck_etl_batch_row_counts
        CHECK (
            input_row_count >= 0
            AND loaded_row_count >= 0
            AND rejected_row_count >= 0
            AND loaded_row_count + rejected_row_count <= input_row_count
        )
);


-- ---------------------------------------------------------------------------
-- Conformed dimensions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100),
    city VARCHAR(100) NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    hash_diff CHAR(64) NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_customer_version
        UNIQUE (customer_id, valid_from),
    CONSTRAINT fk_dim_customer_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_dim_customer_valid_period
        CHECK (
            (is_current AND valid_to IS NULL)
            OR
            (NOT is_current AND valid_to IS NOT NULL AND valid_to > valid_from)
        ),
    CONSTRAINT ex_dim_customer_no_overlap
        EXCLUDE USING GIST (
            customer_id WITH =,
            tstzrange(valid_from, valid_to, '[)') WITH &&
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_customer_current
    ON dim_customer (customer_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_customer_batch
    ON dim_customer (batch_id);


CREATE TABLE IF NOT EXISTS dim_restaurant (
    restaurant_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    restaurant_name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    hash_diff CHAR(64) NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_restaurant_version
        UNIQUE (restaurant_id, valid_from),
    CONSTRAINT fk_dim_restaurant_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_dim_restaurant_valid_period
        CHECK (
            (is_current AND valid_to IS NULL)
            OR
            (NOT is_current AND valid_to IS NOT NULL AND valid_to > valid_from)
        ),
    CONSTRAINT ex_dim_restaurant_no_overlap
        EXCLUDE USING GIST (
            restaurant_id WITH =,
            tstzrange(valid_from, valid_to, '[)') WITH &&
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_restaurant_current
    ON dim_restaurant (restaurant_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_restaurant_batch
    ON dim_restaurant (batch_id);


CREATE TABLE IF NOT EXISTS dim_menu_item (
    menu_item_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id VARCHAR(50) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    menu_item_name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    base_price NUMERIC(12, 2) NOT NULL,
    available BOOLEAN NOT NULL,
    tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    hash_diff CHAR(64) NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_menu_item_version
        UNIQUE (menu_item_id, valid_from),
    CONSTRAINT fk_dim_menu_item_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_dim_menu_item_base_price
        CHECK (base_price >= 0),
    CONSTRAINT ck_dim_menu_item_valid_period
        CHECK (
            (is_current AND valid_to IS NULL)
            OR
            (NOT is_current AND valid_to IS NOT NULL AND valid_to > valid_from)
        ),
    CONSTRAINT ex_dim_menu_item_no_overlap
        EXCLUDE USING GIST (
            menu_item_id WITH =,
            tstzrange(valid_from, valid_to, '[)') WITH &&
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_menu_item_current
    ON dim_menu_item (menu_item_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_menu_item_restaurant
    ON dim_menu_item (restaurant_id);

CREATE INDEX IF NOT EXISTS idx_dim_menu_item_batch
    ON dim_menu_item (batch_id);


CREATE TABLE IF NOT EXISTS dim_driver (
    driver_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    driver_name VARCHAR(255) NOT NULL,
    number_plate VARCHAR(50),
    driver_status VARCHAR(50) NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    hash_diff CHAR(64) NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_driver_version
        UNIQUE (driver_id, valid_from),
    CONSTRAINT fk_dim_driver_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_dim_driver_valid_period
        CHECK (
            (is_current AND valid_to IS NULL)
            OR
            (NOT is_current AND valid_to IS NOT NULL AND valid_to > valid_from)
        ),
    CONSTRAINT ex_dim_driver_no_overlap
        EXCLUDE USING GIST (
            driver_id WITH =,
            tstzrange(valid_from, valid_to, '[)') WITH &&
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_driver_current
    ON dim_driver (driver_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_driver_batch
    ON dim_driver (batch_id);


CREATE TABLE IF NOT EXISTS dim_payment_method (
    payment_method_key SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method_code VARCHAR(50) NOT NULL UNIQUE,
    payment_method_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE UNIQUE,
    day_of_month SMALLINT,
    day_of_week SMALLINT,
    day_name VARCHAR(20),
    week_of_year SMALLINT,
    month_number SMALLINT,
    month_name VARCHAR(20),
    quarter_number SMALLINT,
    year_number INTEGER,
    is_weekend BOOLEAN,

    CONSTRAINT ck_dim_date_unknown_or_complete
        CHECK (
            (
                date_key = 0
                AND full_date IS NULL
                AND day_of_month IS NULL
                AND day_of_week IS NULL
                AND day_name IS NULL
                AND week_of_year IS NULL
                AND month_number IS NULL
                AND month_name IS NULL
                AND quarter_number IS NULL
                AND year_number IS NULL
                AND is_weekend IS NULL
            )
            OR
            (
                date_key > 0
                AND full_date IS NOT NULL
                AND day_of_month BETWEEN 1 AND 31
                AND day_of_week BETWEEN 1 AND 7
                AND day_name IS NOT NULL
                AND week_of_year BETWEEN 1 AND 53
                AND month_number BETWEEN 1 AND 12
                AND month_name IS NOT NULL
                AND quarter_number BETWEEN 1 AND 4
                AND year_number IS NOT NULL
                AND is_weekend IS NOT NULL
                AND date_key = TO_CHAR(full_date, 'YYYYMMDD')::INTEGER
            )
        )
);


-- ---------------------------------------------------------------------------
-- Facts
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fact_order (
    order_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    customer_key BIGINT NOT NULL,
    restaurant_key BIGINT NOT NULL,
    order_date_key INTEGER NOT NULL,
    order_status VARCHAR(50) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) NOT NULL,
    delivery_fee NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    ordered_at TIMESTAMPTZ NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_order_customer
        FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key),
    CONSTRAINT fk_fact_order_restaurant
        FOREIGN KEY (restaurant_key) REFERENCES dim_restaurant (restaurant_key),
    CONSTRAINT fk_fact_order_date
        FOREIGN KEY (order_date_key) REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_order_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_fact_order_amounts
        CHECK (
            subtotal >= 0
            AND discount >= 0
            AND delivery_fee >= 0
            AND total_amount >= 0
            AND total_amount = subtotal - discount + delivery_fee
        )
);

CREATE INDEX IF NOT EXISTS idx_fact_order_customer
    ON fact_order (customer_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_restaurant
    ON fact_order (restaurant_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_date
    ON fact_order (order_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_batch
    ON fact_order (batch_id);


CREATE TABLE IF NOT EXISTS fact_order_item (
    order_item_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    customer_key BIGINT NOT NULL,
    restaurant_key BIGINT NOT NULL,
    menu_item_key BIGINT NOT NULL,
    order_date_key INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    ordered_at TIMESTAMPTZ NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_order_item_customer
        FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key),
    CONSTRAINT fk_fact_order_item_restaurant
        FOREIGN KEY (restaurant_key) REFERENCES dim_restaurant (restaurant_key),
    CONSTRAINT fk_fact_order_item_menu_item
        FOREIGN KEY (menu_item_key) REFERENCES dim_menu_item (menu_item_key),
    CONSTRAINT fk_fact_order_item_date
        FOREIGN KEY (order_date_key) REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_order_item_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_fact_order_item_values
        CHECK (
            quantity > 0
            AND unit_price >= 0
            AND total_price >= 0
            AND total_price = quantity * unit_price
        )
);

CREATE INDEX IF NOT EXISTS idx_fact_order_item_order
    ON fact_order_item (order_id);
CREATE INDEX IF NOT EXISTS idx_fact_order_item_customer
    ON fact_order_item (customer_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_item_restaurant
    ON fact_order_item (restaurant_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_item_menu_item
    ON fact_order_item (menu_item_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_item_date
    ON fact_order_item (order_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_order_item_batch
    ON fact_order_item (batch_id);


CREATE TABLE IF NOT EXISTS fact_payment (
    payment_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    customer_key BIGINT NOT NULL,
    restaurant_key BIGINT NOT NULL,
    payment_method_key SMALLINT NOT NULL,
    payment_created_date_key INTEGER NOT NULL,
    paid_date_key INTEGER NOT NULL DEFAULT 0,
    payment_status VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    transaction_ref VARCHAR(100),
    payment_created_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_payment_customer
        FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key),
    CONSTRAINT fk_fact_payment_restaurant
        FOREIGN KEY (restaurant_key) REFERENCES dim_restaurant (restaurant_key),
    CONSTRAINT fk_fact_payment_method
        FOREIGN KEY (payment_method_key)
        REFERENCES dim_payment_method (payment_method_key),
    CONSTRAINT fk_fact_payment_created_date
        FOREIGN KEY (payment_created_date_key) REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_payment_paid_date
        FOREIGN KEY (paid_date_key) REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_payment_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_fact_payment_amount
        CHECK (amount >= 0),
    CONSTRAINT ck_fact_payment_paid_at
        CHECK (paid_at IS NULL OR paid_at >= payment_created_at)
);

CREATE INDEX IF NOT EXISTS idx_fact_payment_order
    ON fact_payment (order_id);
CREATE INDEX IF NOT EXISTS idx_fact_payment_customer
    ON fact_payment (customer_key);
CREATE INDEX IF NOT EXISTS idx_fact_payment_restaurant
    ON fact_payment (restaurant_key);
CREATE INDEX IF NOT EXISTS idx_fact_payment_method
    ON fact_payment (payment_method_key);
CREATE INDEX IF NOT EXISTS idx_fact_payment_created_date
    ON fact_payment (payment_created_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_payment_paid_date
    ON fact_payment (paid_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_payment_batch
    ON fact_payment (batch_id);


CREATE TABLE IF NOT EXISTS fact_delivery_attempt (
    delivery_attempt_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    customer_key BIGINT NOT NULL,
    restaurant_key BIGINT NOT NULL,
    driver_key BIGINT NOT NULL,
    assigned_date_key INTEGER NOT NULL,
    delivery_status VARCHAR(50) NOT NULL,
    distance_km NUMERIC(8, 2) NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL,
    picked_up_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    source_updated_at TIMESTAMPTZ NOT NULL,
    batch_id UUID NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_delivery_customer
        FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key),
    CONSTRAINT fk_fact_delivery_restaurant
        FOREIGN KEY (restaurant_key) REFERENCES dim_restaurant (restaurant_key),
    CONSTRAINT fk_fact_delivery_driver
        FOREIGN KEY (driver_key) REFERENCES dim_driver (driver_key),
    CONSTRAINT fk_fact_delivery_date
        FOREIGN KEY (assigned_date_key) REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_delivery_batch
        FOREIGN KEY (batch_id) REFERENCES etl_batch (batch_id),
    CONSTRAINT ck_fact_delivery_distance
        CHECK (distance_km > 0 AND distance_km <= 200),
    CONSTRAINT ck_fact_delivery_timeline
        CHECK (
            (picked_up_at IS NULL OR picked_up_at >= assigned_at)
            AND
            (
                delivered_at IS NULL
                OR (picked_up_at IS NOT NULL AND delivered_at >= picked_up_at)
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_fact_delivery_order
    ON fact_delivery_attempt (order_id);
CREATE INDEX IF NOT EXISTS idx_fact_delivery_customer
    ON fact_delivery_attempt (customer_key);
CREATE INDEX IF NOT EXISTS idx_fact_delivery_restaurant
    ON fact_delivery_attempt (restaurant_key);
CREATE INDEX IF NOT EXISTS idx_fact_delivery_driver
    ON fact_delivery_attempt (driver_key);
CREATE INDEX IF NOT EXISTS idx_fact_delivery_date
    ON fact_delivery_attempt (assigned_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_delivery_batch
    ON fact_delivery_attempt (batch_id);


COMMENT ON SCHEMA warehouse IS
    'Food-delivery analytical warehouse using conformed dimensions and four facts.';

COMMENT ON COLUMN fact_payment.amount IS
    'Positive source payment amount; REFUNDED is represented by payment_status.';

COMMENT ON COLUMN fact_order_item.ordered_at IS
    'Order event timestamp derived by joining the source item to its parent order.';

COMMENT ON COLUMN dim_date.date_key IS
    'Business date in Asia/Bangkok as YYYYMMDD; 0 is the unknown member.';

COMMIT;
