services:
  mongodb:
    image: mongo:8.0
    container_name: food-delivery-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.4
    container_name: food-delivery-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: food_delivery_source
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./source/init_table.sql:/docker-entrypoint-initdb.d/01-init.sql:ro


volumes:
  mongodb_data:
  mysql_data: