-- Run this script with the dedicated ETL role after the account-level
-- database, schemas, warehouse, user, and grants have been created.
USE ROLE FOOD_DELIVERY_ETL_ROLE;
USE WAREHOUSE FOOD_DELIVERY_WH;
USE DATABASE FOOD_DELIVERY_DW;


-- ETL batch control


CREATE TABLE IF NOT EXISTS WAREHOUSE.ETL_BATCH (
    BATCH_ID VARCHAR(36) NOT NULL,
    PIPELINE_NAME VARCHAR(100) NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    BATCH_STATUS VARCHAR(20) NOT NULL,
    MYSQL_WATERMARK_FROM TIMESTAMP_TZ,
    MYSQL_WATERMARK_TO TIMESTAMP_TZ,
    MONGO_WATERMARK_FROM TIMESTAMP_TZ,
    MONGO_WATERMARK_TO TIMESTAMP_TZ,
    INPUT_ROW_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    LOADED_ROW_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    REJECTED_ROW_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    ERROR_MESSAGE VARCHAR,

    CONSTRAINT PK_ETL_BATCH
        PRIMARY KEY (BATCH_ID),
    CONSTRAINT CK_ETL_BATCH_STATUS
        CHECK (
            BATCH_STATUS IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')
        ),
    CONSTRAINT CK_ETL_BATCH_COMPLETED_AT
        CHECK (
            COMPLETED_AT IS NULL
            OR COMPLETED_AT >= STARTED_AT
        ),
    CONSTRAINT CK_ETL_BATCH_ROW_COUNTS
        CHECK (
            INPUT_ROW_COUNT >= 0
            AND LOADED_ROW_COUNT >= 0
            AND REJECTED_ROW_COUNT >= 0
            AND LOADED_ROW_COUNT + REJECTED_ROW_COUNT <= INPUT_ROW_COUNT
        )
);

-- Customer staging

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.CUSTOMER (
    BATCH_ID VARCHAR(36) NOT NULL,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(100),
    CITY VARCHAR(100) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_CUSTOMER
        PRIMARY KEY (BATCH_ID, CUSTOMER_ID)
);

-- Customer dimension: SCD Type 2

CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(100),
    CITY VARCHAR(100) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_CUSTOMER
        PRIMARY KEY (CUSTOMER_KEY),
    CONSTRAINT UQ_DIM_CUSTOMER_VERSION
        UNIQUE (CUSTOMER_ID, VALID_FROM),
    CONSTRAINT FK_DIM_CUSTOMER_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_DIM_CUSTOMER_ID
        CHECK (CUSTOMER_ID >= 0),
    CONSTRAINT CK_DIM_CUSTOMER_HASH
        CHECK (LENGTH(HASH_DIFF) = 64),
    CONSTRAINT CK_DIM_CUSTOMER_VALID_PERIOD
        CHECK (
            (
                IS_CURRENT = TRUE
                AND VALID_TO IS NULL
            )
            OR
            (
                IS_CURRENT = FALSE
                AND VALID_TO IS NOT NULL
                AND VALID_TO > VALID_FROM
            )
        ),
    CONSTRAINT CK_DIM_CUSTOMER_SOURCE_TIME
        CHECK (SOURCE_UPDATED_AT >= VALID_FROM)
);

-- Restaurant staging 

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.RESTAURANT (
    BATCH_ID VARCHAR(36) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    STATUS VARCHAR(50) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_RESTAURANT
        PRIMARY KEY (BATCH_ID, RESTAURANT_ID)
);

-- Restaurant dimension: SCD Type 2

CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_RESTAURANT (
    RESTAURANT_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    STATUS VARCHAR(50) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_RESTAURANT
        PRIMARY KEY (RESTAURANT_KEY),
    CONSTRAINT UQ_DIM_RESTAURANT_VERSION
        UNIQUE (RESTAURANT_ID, VALID_FROM),
    CONSTRAINT FK_DIM_RESTAURANT_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_DIM_RESTAURANT_ID
        CHECK (RESTAURANT_ID >= 0),
    CONSTRAINT CK_DIM_RESTAURANT_HASH
        CHECK (LENGTH(HASH_DIFF) = 64),
    CONSTRAINT CK_DIM_RESTAURANT_VALID_PERIOD
        CHECK (
            (
                IS_CURRENT = TRUE
                AND VALID_TO IS NULL
            )
            OR
            (
                IS_CURRENT = FALSE
                AND VALID_TO IS NOT NULL
                AND VALID_TO > VALID_FROM
            )
        ),
    CONSTRAINT CK_DIM_RESTAURANT_SOURCE_TIME
        CHECK (SOURCE_UPDATED_AT >= VALID_FROM)
);


-- ---------------------------------------------------------------------------
-- Driver staging
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.DRIVER (
    BATCH_ID VARCHAR(36) NOT NULL,
    DRIVER_ID NUMBER(38, 0) NOT NULL,
    DRIVER_NAME VARCHAR(255) NOT NULL,
    NUMBER_PLATE VARCHAR(50) NOT NULL,
    DRIVER_STATUS VARCHAR(50) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_DRIVER
        PRIMARY KEY (BATCH_ID, DRIVER_ID)
);


-- ---------------------------------------------------------------------------
-- Driver dimension: SCD Type 2
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_DRIVER (
    DRIVER_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    DRIVER_ID NUMBER(38, 0) NOT NULL,
    DRIVER_NAME VARCHAR(255) NOT NULL,
    NUMBER_PLATE VARCHAR(50) NOT NULL,
    DRIVER_STATUS VARCHAR(50) NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_DRIVER
        PRIMARY KEY (DRIVER_KEY),
    CONSTRAINT UQ_DIM_DRIVER_VERSION
        UNIQUE (DRIVER_ID, VALID_FROM),
    CONSTRAINT FK_DIM_DRIVER_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_DIM_DRIVER_ID
        CHECK (DRIVER_ID >= 0),
    CONSTRAINT CK_DIM_DRIVER_HASH
        CHECK (LENGTH(HASH_DIFF) = 64),
    CONSTRAINT CK_DIM_DRIVER_VALID_PERIOD
        CHECK (
            (
                IS_CURRENT = TRUE
                AND VALID_TO IS NULL
            )
            OR
            (
                IS_CURRENT = FALSE
                AND VALID_TO IS NOT NULL
                AND VALID_TO > VALID_FROM
            )
        ),
    CONSTRAINT CK_DIM_DRIVER_SOURCE_TIME
        CHECK (SOURCE_UPDATED_AT >= VALID_FROM)
);


-- ---------------------------------------------------------------------------
-- Menu-item staging
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.MENU_ITEM (
    BATCH_ID VARCHAR(36) NOT NULL,
    MENU_ITEM_ID VARCHAR(50) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    MENU_ITEM_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    BASE_PRICE NUMBER(12, 2) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    TAGS_JSON VARCHAR NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_MENU_ITEM
        PRIMARY KEY (BATCH_ID, MENU_ITEM_ID)
);


-- ---------------------------------------------------------------------------
-- Menu-item dimension: SCD Type 2
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_MENU_ITEM (
    MENU_ITEM_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    MENU_ITEM_ID VARCHAR(50) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    MENU_ITEM_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    BASE_PRICE NUMBER(12, 2) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    TAGS ARRAY NOT NULL,
    VALID_FROM TIMESTAMP_TZ NOT NULL,
    VALID_TO TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    HASH_DIFF VARCHAR(64) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_MENU_ITEM
        PRIMARY KEY (MENU_ITEM_KEY),
    CONSTRAINT UQ_DIM_MENU_ITEM_VERSION
        UNIQUE (MENU_ITEM_ID, VALID_FROM),
    CONSTRAINT FK_DIM_MENU_ITEM_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_DIM_MENU_ITEM_ID
        CHECK (LENGTH(MENU_ITEM_ID) > 0),
    CONSTRAINT CK_DIM_MENU_ITEM_RESTAURANT
        CHECK (RESTAURANT_ID >= 0),
    CONSTRAINT CK_DIM_MENU_ITEM_PRICE
        CHECK (BASE_PRICE >= 0),
    CONSTRAINT CK_DIM_MENU_ITEM_HASH
        CHECK (LENGTH(HASH_DIFF) = 64),
    CONSTRAINT CK_DIM_MENU_ITEM_VALID_PERIOD
        CHECK (
            (
                IS_CURRENT = TRUE
                AND VALID_TO IS NULL
            )
            OR
            (
                IS_CURRENT = FALSE
                AND VALID_TO IS NOT NULL
                AND VALID_TO > VALID_FROM
            )
        ),
    CONSTRAINT CK_DIM_MENU_ITEM_SOURCE_TIME
        CHECK (SOURCE_UPDATED_AT >= VALID_FROM)
);


-- ---------------------------------------------------------------------------
-- Static conformed dimensions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_PAYMENT_METHOD (
    PAYMENT_METHOD_KEY NUMBER(5, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    PAYMENT_METHOD_CODE VARCHAR(50) NOT NULL,
    PAYMENT_METHOD_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_DIM_PAYMENT_METHOD
        PRIMARY KEY (PAYMENT_METHOD_KEY),
    CONSTRAINT UQ_DIM_PAYMENT_METHOD_CODE
        UNIQUE (PAYMENT_METHOD_CODE)
);


CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_DATE (
    DATE_KEY NUMBER(8, 0) NOT NULL,
    FULL_DATE DATE,
    DAY_OF_MONTH NUMBER(2, 0),
    DAY_OF_WEEK NUMBER(1, 0),
    DAY_NAME VARCHAR(20),
    WEEK_OF_YEAR NUMBER(2, 0),
    MONTH_NUMBER NUMBER(2, 0),
    MONTH_NAME VARCHAR(20),
    QUARTER_NUMBER NUMBER(1, 0),
    YEAR_NUMBER NUMBER(4, 0),
    IS_WEEKEND BOOLEAN,

    CONSTRAINT PK_DIM_DATE
        PRIMARY KEY (DATE_KEY),
    CONSTRAINT UQ_DIM_DATE_FULL_DATE
        UNIQUE (FULL_DATE),
    CONSTRAINT CK_DIM_DATE_UNKNOWN_OR_COMPLETE
        CHECK (
            (
                DATE_KEY = 0
                AND FULL_DATE IS NULL
                AND DAY_OF_MONTH IS NULL
                AND DAY_OF_WEEK IS NULL
                AND DAY_NAME IS NULL
                AND WEEK_OF_YEAR IS NULL
                AND MONTH_NUMBER IS NULL
                AND MONTH_NAME IS NULL
                AND QUARTER_NUMBER IS NULL
                AND YEAR_NUMBER IS NULL
                AND IS_WEEKEND IS NULL
            )
            OR
            (
                DATE_KEY > 0
                AND FULL_DATE IS NOT NULL
                AND DAY_OF_MONTH BETWEEN 1 AND 31
                AND DAY_OF_WEEK BETWEEN 1 AND 7
                AND DAY_NAME IS NOT NULL
                AND WEEK_OF_YEAR BETWEEN 1 AND 53
                AND MONTH_NUMBER BETWEEN 1 AND 12
                AND MONTH_NAME IS NOT NULL
                AND QUARTER_NUMBER BETWEEN 1 AND 4
                AND YEAR_NUMBER IS NOT NULL
                AND IS_WEEKEND IS NOT NULL
                AND DATE_KEY = TO_NUMBER(
                    TO_CHAR(FULL_DATE, 'YYYYMMDD')
                )
            )
        )
);


-- ---------------------------------------------------------------------------
-- Order staging
-- Spark contract: transform/order.py -> warehouse_orders
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.ORDERS (
    BATCH_ID VARCHAR(36) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8, 0) NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    SUBTOTAL NUMBER(12, 2) NOT NULL,
    DISCOUNT NUMBER(12, 2) NOT NULL,
    DELIVERY_FEE NUMBER(12, 2) NOT NULL,
    TOTAL_AMOUNT NUMBER(12, 2) NOT NULL,
    ORDERED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_ORDERS
        PRIMARY KEY (BATCH_ID, ORDER_ID)
);


-- ---------------------------------------------------------------------------
-- Order fact
-- Grain: one row per source order
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.FACT_ORDER (
    ORDER_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_KEY NUMBER(38, 0) NOT NULL,
    RESTAURANT_KEY NUMBER(38, 0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8, 0) NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    SUBTOTAL NUMBER(12, 2) NOT NULL,
    DISCOUNT NUMBER(12, 2) NOT NULL,
    DELIVERY_FEE NUMBER(12, 2) NOT NULL,
    TOTAL_AMOUNT NUMBER(12, 2) NOT NULL,
    ORDERED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_ORDER
        PRIMARY KEY (ORDER_KEY),
    CONSTRAINT UQ_FACT_ORDER_ID
        UNIQUE (ORDER_ID),
    CONSTRAINT FK_FACT_ORDER_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES WAREHOUSE.DIM_CUSTOMER (CUSTOMER_KEY),
    CONSTRAINT FK_FACT_ORDER_RESTAURANT
        FOREIGN KEY (RESTAURANT_KEY)
        REFERENCES WAREHOUSE.DIM_RESTAURANT (RESTAURANT_KEY),
    CONSTRAINT FK_FACT_ORDER_DATE
        FOREIGN KEY (ORDER_DATE_KEY)
        REFERENCES WAREHOUSE.DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_ORDER_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_FACT_ORDER_STATUS
        CHECK (
            ORDER_STATUS IN ('DELIVERED', 'CANCELLED', 'PREPARING')
        ),
    CONSTRAINT CK_FACT_ORDER_AMOUNTS
        CHECK (
            SUBTOTAL >= 0
            AND DISCOUNT >= 0
            AND DELIVERY_FEE >= 0
            AND TOTAL_AMOUNT >= 0
            AND TOTAL_AMOUNT = SUBTOTAL - DISCOUNT + DELIVERY_FEE
        )
);


-- ---------------------------------------------------------------------------
-- Order-item staging
-- Spark contract: transform/order_item.py -> warehouse_order_items
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.ORDER_ITEM (
    BATCH_ID VARCHAR(36) NOT NULL,
    ORDER_ITEM_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    MENU_ITEM_ID VARCHAR(50) NOT NULL,
    ORDER_DATE_KEY NUMBER(8, 0) NOT NULL,
    QUANTITY NUMBER(38, 0) NOT NULL,
    UNIT_PRICE NUMBER(12, 2) NOT NULL,
    TOTAL_PRICE NUMBER(12, 2) NOT NULL,
    ORDERED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_ORDER_ITEM
        PRIMARY KEY (BATCH_ID, ORDER_ITEM_ID)
);


-- ---------------------------------------------------------------------------
-- Order-item fact
-- Grain: one menu-item line within an order
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.FACT_ORDER_ITEM (
    ORDER_ITEM_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ITEM_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_KEY NUMBER(38, 0) NOT NULL,
    RESTAURANT_KEY NUMBER(38, 0) NOT NULL,
    MENU_ITEM_KEY NUMBER(38, 0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8, 0) NOT NULL,
    QUANTITY NUMBER(38, 0) NOT NULL,
    UNIT_PRICE NUMBER(12, 2) NOT NULL,
    TOTAL_PRICE NUMBER(12, 2) NOT NULL,
    ORDERED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_ORDER_ITEM
        PRIMARY KEY (ORDER_ITEM_KEY),
    CONSTRAINT UQ_FACT_ORDER_ITEM_ID
        UNIQUE (ORDER_ITEM_ID),
    CONSTRAINT FK_FACT_ORDER_ITEM_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES WAREHOUSE.DIM_CUSTOMER (CUSTOMER_KEY),
    CONSTRAINT FK_FACT_ORDER_ITEM_RESTAURANT
        FOREIGN KEY (RESTAURANT_KEY)
        REFERENCES WAREHOUSE.DIM_RESTAURANT (RESTAURANT_KEY),
    CONSTRAINT FK_FACT_ORDER_ITEM_MENU_ITEM
        FOREIGN KEY (MENU_ITEM_KEY)
        REFERENCES WAREHOUSE.DIM_MENU_ITEM (MENU_ITEM_KEY),
    CONSTRAINT FK_FACT_ORDER_ITEM_DATE
        FOREIGN KEY (ORDER_DATE_KEY)
        REFERENCES WAREHOUSE.DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_ORDER_ITEM_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_FACT_ORDER_ITEM_VALUES
        CHECK (
            QUANTITY > 0
            AND UNIT_PRICE >= 0
            AND TOTAL_PRICE >= 0
            AND TOTAL_PRICE = QUANTITY * UNIT_PRICE
        )
);


-- ---------------------------------------------------------------------------
-- Payment staging
-- Spark contract: transform/payment.py -> warehouse_payments
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.PAYMENT (
    BATCH_ID VARCHAR(36) NOT NULL,
    PAYMENT_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    PAYMENT_METHOD VARCHAR(50) NOT NULL,
    PAYMENT_CREATED_DATE_KEY NUMBER(8, 0) NOT NULL,
    PAID_DATE_KEY NUMBER(8, 0) NOT NULL,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    AMOUNT NUMBER(12, 2) NOT NULL,
    TRANSACTION_REF VARCHAR(100),
    PAYMENT_CREATED_AT TIMESTAMP_TZ NOT NULL,
    PAID_AT TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_PAYMENT
        PRIMARY KEY (BATCH_ID, PAYMENT_ID)
);


-- ---------------------------------------------------------------------------
-- Payment fact
-- Grain: one source payment record and its current lifecycle state
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.FACT_PAYMENT (
    PAYMENT_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    PAYMENT_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_KEY NUMBER(38, 0) NOT NULL,
    RESTAURANT_KEY NUMBER(38, 0) NOT NULL,
    PAYMENT_METHOD_KEY NUMBER(5, 0) NOT NULL,
    PAYMENT_CREATED_DATE_KEY NUMBER(8, 0) NOT NULL,
    PAID_DATE_KEY NUMBER(8, 0) NOT NULL DEFAULT 0,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    AMOUNT NUMBER(12, 2) NOT NULL,
    TRANSACTION_REF VARCHAR(100),
    PAYMENT_CREATED_AT TIMESTAMP_TZ NOT NULL,
    PAID_AT TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_PAYMENT
        PRIMARY KEY (PAYMENT_KEY),
    CONSTRAINT UQ_FACT_PAYMENT_ID
        UNIQUE (PAYMENT_ID),
    CONSTRAINT FK_FACT_PAYMENT_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES WAREHOUSE.DIM_CUSTOMER (CUSTOMER_KEY),
    CONSTRAINT FK_FACT_PAYMENT_RESTAURANT
        FOREIGN KEY (RESTAURANT_KEY)
        REFERENCES WAREHOUSE.DIM_RESTAURANT (RESTAURANT_KEY),
    CONSTRAINT FK_FACT_PAYMENT_METHOD
        FOREIGN KEY (PAYMENT_METHOD_KEY)
        REFERENCES WAREHOUSE.DIM_PAYMENT_METHOD (PAYMENT_METHOD_KEY),
    CONSTRAINT FK_FACT_PAYMENT_CREATED_DATE
        FOREIGN KEY (PAYMENT_CREATED_DATE_KEY)
        REFERENCES WAREHOUSE.DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_PAYMENT_PAID_DATE
        FOREIGN KEY (PAID_DATE_KEY)
        REFERENCES WAREHOUSE.DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_PAYMENT_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_FACT_PAYMENT_STATUS
        CHECK (
            PAYMENT_STATUS IN ('PAID', 'PENDING', 'REFUNDED')
        ),
    CONSTRAINT CK_FACT_PAYMENT_AMOUNT
        CHECK (AMOUNT >= 0),
    CONSTRAINT CK_FACT_PAYMENT_TIMELINE
        CHECK (
            PAID_AT IS NULL
            OR PAID_AT >= PAYMENT_CREATED_AT
        ),
    CONSTRAINT CK_FACT_PAYMENT_PAID_DATE
        CHECK (
            (
                PAID_AT IS NULL
                AND PAID_DATE_KEY = 0
            )
            OR
            (
                PAID_AT IS NOT NULL
                AND PAID_DATE_KEY > 0
            )
        )
);


-- ---------------------------------------------------------------------------
-- Delivery staging
-- Spark contract: transform/delivery.py -> warehouse_deliveries
-- ---------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS STAGING.DELIVERY (
    BATCH_ID VARCHAR(36) NOT NULL,
    DELIVERY_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_ID NUMBER(38, 0) NOT NULL,
    RESTAURANT_ID NUMBER(38, 0) NOT NULL,
    DRIVER_ID NUMBER(38, 0) NOT NULL,
    ASSIGNED_DATE_KEY NUMBER(8, 0) NOT NULL,
    DELIVERY_STATUS VARCHAR(50) NOT NULL,
    DISTANCE_KM NUMBER(8, 2) NOT NULL,
    ASSIGNED_AT TIMESTAMP_TZ NOT NULL,
    PICKED_UP_AT TIMESTAMP_TZ,
    DELIVERED_AT TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,

    CONSTRAINT PK_STAGING_DELIVERY
        PRIMARY KEY (BATCH_ID, DELIVERY_ID)
);


-- ---------------------------------------------------------------------------
-- Delivery-attempt fact
-- Grain: one source delivery attempt for an order
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS WAREHOUSE.FACT_DELIVERY_ATTEMPT (
    DELIVERY_ATTEMPT_KEY NUMBER(38, 0)
        NOT NULL
        AUTOINCREMENT START 1 INCREMENT 1,
    DELIVERY_ID NUMBER(38, 0) NOT NULL,
    ORDER_ID NUMBER(38, 0) NOT NULL,
    CUSTOMER_KEY NUMBER(38, 0) NOT NULL,
    RESTAURANT_KEY NUMBER(38, 0) NOT NULL,
    DRIVER_KEY NUMBER(38, 0) NOT NULL,
    ASSIGNED_DATE_KEY NUMBER(8, 0) NOT NULL,
    DELIVERY_STATUS VARCHAR(50) NOT NULL,
    DISTANCE_KM NUMBER(8, 2) NOT NULL,
    ASSIGNED_AT TIMESTAMP_TZ NOT NULL,
    PICKED_UP_AT TIMESTAMP_TZ,
    DELIVERED_AT TIMESTAMP_TZ,
    SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR(36) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_DELIVERY_ATTEMPT
        PRIMARY KEY (DELIVERY_ATTEMPT_KEY),
    CONSTRAINT UQ_FACT_DELIVERY_ID
        UNIQUE (DELIVERY_ID),
    CONSTRAINT FK_FACT_DELIVERY_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES WAREHOUSE.DIM_CUSTOMER (CUSTOMER_KEY),
    CONSTRAINT FK_FACT_DELIVERY_RESTAURANT
        FOREIGN KEY (RESTAURANT_KEY)
        REFERENCES WAREHOUSE.DIM_RESTAURANT (RESTAURANT_KEY),
    CONSTRAINT FK_FACT_DELIVERY_DRIVER
        FOREIGN KEY (DRIVER_KEY)
        REFERENCES WAREHOUSE.DIM_DRIVER (DRIVER_KEY),
    CONSTRAINT FK_FACT_DELIVERY_DATE
        FOREIGN KEY (ASSIGNED_DATE_KEY)
        REFERENCES WAREHOUSE.DIM_DATE (DATE_KEY),
    CONSTRAINT FK_FACT_DELIVERY_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES WAREHOUSE.ETL_BATCH (BATCH_ID),
    CONSTRAINT CK_FACT_DELIVERY_STATUS
        CHECK (
            DELIVERY_STATUS IN ('ASSIGNED', 'DELIVERED')
        ),
    CONSTRAINT CK_FACT_DELIVERY_DISTANCE
        CHECK (
            DISTANCE_KM > 0
            AND DISTANCE_KM <= 200
        ),
    CONSTRAINT CK_FACT_DELIVERY_TIMELINE
        CHECK (
            (
                PICKED_UP_AT IS NULL
                OR PICKED_UP_AT >= ASSIGNED_AT
            )
            AND
            (
                DELIVERED_AT IS NULL
                OR (
                    PICKED_UP_AT IS NOT NULL
                    AND DELIVERED_AT >= PICKED_UP_AT
                )
            )
        )
);
